### ISSUE TITLE
Feature Request: Add Dark/Light Mode Toggle Option in Control Panel

### ISSUE THREAD

**Issue by Pranay018977** [AgustinSRG/Showdown-ChatBot#17]
Hi,

I would like to request the addition of an option in the control panel positioned in the top left corner that allows users to toggle between dark mode and light mode. This enhancement would improve usability in different lighting conditions and offer a more customizable user experience.

Thank you for considering this suggestion.

**Comment by Pranay018977** [comment]
I would also like to ask if it would be possible to implement the dark mode to resemble GitHub’s dark mode. This would provide a modern, familiar aesthetic that many users appreciate.

Thank you for considering this enhancement.

**Comment by Pranay018977** [comment]
I wanted to bring to your attention that in the current dark mode on the control panel, the text is somewhat difficult to read. Could you please consider adjusting the contrast or text color to improve readability?

**Comment by AgustinSRG** [comment]
> Hi,
> 
> I would like to request the addition of an option in the control panel positioned in the top left corner that allows users to toggle between dark mode and light mode. This enhancement would improve usability in different lighting conditions and offer a more customizable user experience.
> 
> Thank you for considering this suggestion.

Added by 6e99e8a6731c9cf59ff62851b132e41e589acc48

I positioned it in the footer instead, since I did not like how it looks at the top.

> I wanted to bring to your attention that in the current dark mode on the control panel, the text is somewhat difficult to read. Could you please consider adjusting the contrast or text color to improve readability?

The dark theme is currently experimental, since the control panel almost had no css before. The current color scheme can be found in the [style.css](https://github.com/AgustinSRG/Showdown-ChatBot/blob/master/static/style.css) file.

If you have any color change suggestions that would improve the readability of the text, please provide them. For me it looks good, so it is hard to tell what may be wrong.

**Comment by Pranay018977** [comment]
```css

/* Improved CSS for Light and Dark Themes */

:root {
  /* Light Theme */
  --background-color: #ffffff;
  --text-color: #000000;

  --link-color: #0000EE;
  --link-visited-color: #551A8B;
  --link-active-color: #FF0000;

  --main-div-background: #F8FBFD;
  --main-div-border-color: #BBCCDD;

  --error-color: #FF0000;
  --success-color: #00FF00;

  --menu-option-color-base: #0000FF;
  --menu-option-color-hover: #000033;
  --menu-option-color-selected: #000000;

  --btn-background: #e3e3e3;
  --btn-box-shadow: 0 1px 2px rgba(0,0,0,0.2), inset 0 -1px 2px rgba(255,255,255,1);
  --btn-border-color: #AAAAAA;
  --btn-text-shadow: 0 1px 0 white;
  --btn-text-color: #222222;
  --btn-hover-background: linear-gradient(to bottom, #f2f2f2, #b2b2b2);
  --btn-hover-border: #606060;
  --btn-active-background: linear-gradient(to bottom, #bfbfbf, #f2f2f2);
  --btn-active-border: #AAAAAA;
  --btn-active-box-shadow: 0 1px 2px rgba(0,0,0,0.2), inset 0 -1px 2px rgba(255,255,255,1);

  --input-background: #ffffff;
  --input-text-color: #000000;
  --input-border-color: gray;
  --input-border-color-focus: black;
}

@media (prefers-color-scheme: dark) {
  :root {
    /* Dark Theme */
    --background-color: #151b23;
    --text-color: #ffffff;

    --link-color: #4493f8;
    --link-visited-color: #6d4b8d;
    --link-active-color: #ff4040;

    --main-div-background: #0d1117;
    --main-div-border-color: rgba(255, 255, 255, 0.1);

    --error-color: #FF0000;
    --success-color: #00FF00;

    --menu-option-color-base: #4493f8;
    --menu-option-color-hover: #f9f9f9;
    --menu-option-color-selected: #ffffff;

    --btn-background: #2b2c31;
    --btn-box-shadow: 0.5px 1px 2px rgba(255,255,255,0.45), inset 0.5px 1px 1px rgba(255,255,255,0.5);
    --btn-border-color: #34373b;
    --btn-text-shadow: none;
    --btn-text-color: #F9F9F9;
    --btn-hover-background: #3e4149;
    --btn-hover-border: #50555b;
    --btn-active-background: #2b2c31;
    --btn-active-border: #34373b;
    --btn-active-box-shadow: 0.5px 1px 2px rgba(255,255,255,0.45);

    --input-background: #111111;
    --input-text-color: #DDD;
    --input-border-color: #9199a2;
    --input-border-color-focus: white;
  }
}

/* Base Styles */
body {
  background-color: var(--background-color);
  color: var(--text-color);
  font-family: sans-serif;
  margin: 0;
  padding: 0;
}

a {
  color: var(--link-color);
  text-decoration: none;
}

a:visited {
  color: var(--link-visited-color);
}

a:active {
  color: var(--link-active-color);
}

.maindiv {
  width: 90%;
  background-color: var(--main-div-background);
  margin: 10px auto;
  border: 1px solid var(--main-div-border-color);
  padding: 1em;
  border-radius: 4px;
}

button,
input[type="submit"] {
  border-radius: 5px;
  font-size: 9pt;
  padding: 3px 8px;
  background: var(--btn-background);
  box-shadow: var(--btn-box-shadow);
  border: 1px solid var(--btn-border-color);
  text-shadow: var(--btn-text-shadow);
  color: var(--btn-text-color);
  cursor: pointer;
  transition: background 0.2s, border-color 0.2s;
}

button:hover,
input[type="submit"]:hover {
  background: var(--btn-hover-background);
  border-color: var(--btn-hover-border);
}

button:active,
input[type="submit"]:active {
  background: var(--btn-active-background);
  border-color: var(--btn-active-border);
  box-shadow: var(--btn-active-box-shadow);
}

input,
textarea,
select {
  border-radius: 3px;
  padding: 3px;
  border: 1px solid var(--input-border-color);
  background: var(--input-background);
  color: var(--input-text-color);
  transition: border-color 0.2s;
}

input:focus,
textarea:focus,
select:focus {
  border-color: var(--input-border-color-focus);
  outline: none;
}
```

I’ve shared the CSS code in the previous message, and I trust it will be helpful. Please feel free to use it as you see fit. If any adjustments or further improvements are required, I am happy to provide assistance or discuss suggestions you may have.
